### ISSUE TITLE
error connecting: synology_srm.http.SynologyApiError: Permission denied (error=402)

### ISSUE THREAD

**Issue by maxou330** [gilmrt/srm-exporter#9]
Hi Gilles,

Can't get to connect to my router. The container is launched from a ubuntu server on the same LAN as the router. The router sees the client trying to connect but refuses the connection. No error of course with the password I checked multiple times.
Here's the log

return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/exporter.py", line 413, in updateResults
    system_infos = get_system_info(client)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/exporter.py", line 208, in get_system_info
    system_info = client.http.call(
                  ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/synology_srm/http.py", line 99, in call
    self._login()
  File "/usr/local/lib/python3.12/site-packages/synology_srm/http.py", line 69, in _login
    response = self.call(
               ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/synology_srm/http.py", line 179, in call
    raise SynologyApiError(
synology_srm.http.SynologyApiError: Permission denied (error=402)
ERROR 2024-01-24 14:36:27 Exception on /metrics [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)

**Comment by gilmrt** [comment]
Are you using the account created during the first login?
Permissions needed for the API are only available for **administrator** accounts.

In SRM Control Panel > User, you may notice that an administrator account has a **little gold medal with a red ribbon** on the user icon (as does the default administrator account) which means that the account is part of the administrator group.
If you're not using this primary default admin account, follow steps [here](https://kb.synology.com/en-id/SRM/tutorial/Create_multiple_administrator_accounts_on_Synology_Router) or [here](https://community.synology.com/enu/forum/2/post/127805)to create a new one with admin permissions.

Another idea concerns multi-factor authentication: even if you've disabled two-factor authentication, you still need to click on the administrator account and click on reset multi-factor authentication to disable it for a use that had already enabled it.

I hope this helps

**Comment by maxou330** [comment]
thanks a lot, feel silly, didn't notice the badge as I thought all users on a router were admins...
Then I indeed passed the authentication but now I can't access the metrics here's a new error 1100 with log below:

        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/exporter.py", line 491, in updateResults
    ) = get_traffic_stats(client, mac_to_hostname, mac_to_ip_addr, period)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/exporter.py", line 362, in get_traffic_stats
    ngfw_traffic = client.core.get_ngfw_traffic(interval=period)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/synology_srm/api/core.py", line 63, in get_ngfw_traffic
    return self.http.call(
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/synology_srm/http.py", line 179, in call
    raise SynologyApiError(
synology_srm.http.SynologyApiError: Unknown API error, please check the documentation (error=1100)
INFO 2024-01-25 01:09:38 Total download=7.51 KB Total upload=86.17 KB
ERROR 2024-01-25 01:09:38 Exception on /metrics [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)

**Comment by gilmrt** [comment]
Okay, let's continue...
Too bad error 1100 is unknown
Can you tell me the model of your router and set PERIODS to "live" only like this `PERIODS=live` and maybe try to disable HTTPS verification with `DISABLE_HTTPS_VERIFY=True`
See a full example below

```
---
version: "3.1"
services:
  srm-exporter:
    image: ghcr.io/gilmrt/srm-exporter:latest
    container_name: srm-exporter
    environment:
      - TZ=Europe/Paris
      - SRM_HOST=192.168.1.1
      - SRM_PORT=8001
      - SRM_USERNAME=admin
      - SRM_PASSWORD=password
      - PERIODS=live
      - USE_HTTPS=True
      - DISABLE_HTTPS_VERIFY=True
      - EXPORTER_CACHE_FOR=0
      - EXPORTER_PORT=9922
    ports:
      - 9922:9922
    restart: unless-stopped
```

**Comment by maxou330** [comment]
Great, it worked with your recommandation and it seems it's the "PERIODS" variable that needed adjustment. Indeed, leaving DISABLE_HTTPS_VERIFY to False worked the same but adding anything on top of "live" for PERIODS leads to 1100 error.
My router is the rt6600ax updated with last SRM version.
By the way, I suppose it is normal that the router log shows user login every scrape_interval set in the prometheus yml file? Is it not possible to let a channel from the first session with the user account used for access to the router opened? Unlike DSM (Synology NAS OS) I can't see current user open sessions on the router and I don't know if all the logins every scrape interval lead to multiple parallel sessions so potential router overload in any way (?) or log file explosion.

Relating to the "day" only possible parameter in my case for "PERIODS": does it mean I can get only live data? Or do I (can I) rebuild historical with all the live data gathered over time to replace other parameters?

Thanks

**Comment by gilmrt** [comment]
Good to hear!
You're right about the login, I'll take a look and update some parts of the code.
As for the periods, you should use "live" and let the time series in prometheus do the rest. 
"day", "week" and "month" are just internal SRM time series (available in some models only)

**Comment by maxou330** [comment]
Great thanks for your support and great job on this exporter, I'll play a bit with the metrics waiting for your update on the logins...

**Comment by gilmrt** [comment]
Updated version 2.0.0 can be found [here](https://github.com/users/gilmrt/packages/container/srm-exporter/171194841?tag=2.0.0)
